server:
  error:
    include-message: always
    include-binding-errors: always
  port: 3000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #password: root
    password: root
    url: jdbc:mysql://localhost:3308/rootsandbones
    username: root
  jpa:
    #hibernate.ddl-auto: update
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
